### ISSUE TITLE
Is it possible to set a maximum line length with PMD?

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.formatter.impl#103]
If so, I'd like to enable it and wrap lines where needed.

**Comment by joeha480** [comment]
It's not so easy to enable only certain rules, I don't know if PMD supports it, and I also don't like it.

**Comment by bertfrees** [comment]
Then I misunderstood. I thought the idea was to enable only some checks initially and gradually do more checks.

**Comment by joeha480** [comment]
Sorry I should’ve explained better. It is possible to enable a single category of tests, or enable tests with a level of importance. Depending on where this hypothetical rule is, it might be possible. What I was referring to was just picking one rule, which isn’t very easy, because then you have to manage all rules yourself (I think).
